# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Global Life
email: contacto@global-life.cl
description: > # this means to ignore newlines until "baseurl:"
  Somos una empresa que busca acercar la salud a todos los chilenos, representando y distribuyendo marcas de productos naturales, en donde cada uno de los ingredientes sean reconocibles, sanos y llenos de nutrientes.
baseurl: "https://camargozzini.github.io/globalife/" # the subpath of your site, e.g. /blog
url: "https://camargozzini.github.io/globalife/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  camargozzini

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Translations
t:
  en:
    index:
      about: "About us"
      contact:  "Contact"
      brands: "Our Brands"
      view-brand: "View brand"
  es:
    index:
      about: "Sobre nosotros"
      contact:  "Contacto"
      brands: "Nuestras Marcas"
      view-brand: "Ver marca"
